### ISSUE TITLE
SDK parameters should match API parameters

### ISSUE THREAD

**Issue by andrew-pause** [SparkPost/php-sparkpost#81] opened 2016-04-22 15:24 UTC
I lost an hour debugging an issue last night because I was passing the parameters from your api docs into the transmission::send() method.

**Comment by richleland** [comment] 2016-04-22 18:04
Thanks for the feedback @andrew-pause - I'm going to link and close this out as a dupe of #67 - we'll be making some adjustments to the docs to make this more clear. We'll potentially look at renaming the params in a later release as well.

**Closed by richleland** 2016-04-22 18:04 UTC
